### ISSUE TITLE
MAYA_RENDER_SETUP_GLOBAL_PRESETS_PATH

### ISSUE THREAD

**Issue by AndrewHazelden** [mottosso/Maya-Environment-Variables#1]
As an additional entry to your GitHub project, the `MAYA_RENDER_SETUP_GLOBAL_PRESETS_PATH` environment variable is used to tell Maya where the Maya 2017 Render Settings JSON preset files are stored:

[Create and select a Render Settings preset](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/Maya/files/GUID-469A3F38-8E0B-4A28-8913-D8A7E3EF0733-htm.html)

Cheers,
Andrew Hazelden

**Comment by mottosso** [comment]
Thanks, added, and sorry for the delay; wasn't seeing notifications, but are now!
