### ISSUE TITLE
MAYA_ENABLE_WEBENGINE

### ISSUE THREAD

**Issue by AndrewHazelden** [mottosso/Maya-Environment-Variables#2]
A new `MAYA_ENABLE_WEBENGINE` environment variable was added in Maya 2018.1

See  [MAYA-86221](https://knowledge.autodesk.com/sites/default/files/Maya_2018.1_Update_Readme_enu.htm) on this documentation page for more details.

**Comment by mottosso** [comment]
Thanks, added, and sorry for the delay; wasn't seeing notifications, but are now!
